//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tellisense.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum
    {
        public Forum()
        {
            this.SubForum = new HashSet<SubForum>();
        }
    
        public int forum_ID { get; set; }
        public string forum_Title { get; set; }
        public string forum_description { get; set; }
    
        public virtual ICollection<SubForum> SubForum { get; set; }
    }
}
