//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tellisense.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubForum
    {
        public SubForum()
        {
            this.Thread = new HashSet<Thread>();
        }
    
        public int subforum_ID { get; set; }
        public string subforum_Title { get; set; }
        public string subforum_description { get; set; }
        public int in_forum { get; set; }
    
        public virtual Forum Forum { get; set; }
        public virtual ICollection<Thread> Thread { get; set; }
    }
}
