//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tellisense.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thread
    {
        public Thread()
        {
            this.Post = new HashSet<Post>();
            this.User = new HashSet<User>();
        }
    
        public int thread_ID { get; set; }
        public string thread_Title { get; set; }
        public string thread_description { get; set; }
        public int in_subforum { get; set; }
        public Nullable<int> key_post { get; set; }
        public int view_count { get; set; }
    
        public virtual ICollection<Post> Post { get; set; }
        public virtual Post Post1 { get; set; }
        public virtual SubForum SubForum { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
